version: "3.9"

services:
  phpapp:
    container_name: phpapp
    hostname: phpapp
    build:
      dockerfile: Docker/Dockerfile
    volumes:
      - ./:/var/www/html
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - phpapp
