FROM php:8.2-cli

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --check
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

#will be some dev exstensions

WORKDIR /vaw/www